development:
  adapter: postgresql
  encoding: unicode
  database: launchbook_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: launchbook_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: launchbook_production
  pool: 5
  username:
  password:
